# These are supported funding model platforms

github: [Aaasaasa]
# patreon: # your Patreon username
# open_collective: # your Open Collective username
# ko_fi: # your Ko-fi username
# tidelift: # package-name
# community_bridge: # project-name
# liberapay: # your Liberapay username
# issuehunt: # your IssueHunt username
# otechie: # your Otechie username
# lfx_crowdfunding: # your LFX Crowdfunding project-name
# polar: # your Polar username
custom: ['https://github.com/Aaasaasa'] # Add your PayPal, Buy Me a Coffee, or other links
